import asyncio
import json
import os
from dotenv import load_dotenv

from failure_agent import Failure_Agent
from tools.azure_devops_windows_runner_adapter import (
    AzureDevOpsWindowsSelfHostedRunnerAdapter,
)

load_dotenv()


# ---------------------------------------------------------
# Test-only wrapper:
# Print the commands generated by the LLM when the actual
# Runner Adapter invokes the LLM.
# ---------------------------------------------------------

_original_ask_llm_for_commands = (
    AzureDevOpsWindowsSelfHostedRunnerAdapter._ask_llm_for_commands
)


def _debug_ask_llm_for_commands(
    self,
    technology: str,
    required_version: str,
    available_files: list[str],
):
    result = _original_ask_llm_for_commands(
        self,
        technology,
        required_version,
        available_files,
    )

    print("\n" + "=" * 80)
    print("LLM GENERATED RUNNER COMMANDS")
    print("=" * 80)
    print(json.dumps(result, indent=2))
    print("=" * 80 + "\n")

    return result


AzureDevOpsWindowsSelfHostedRunnerAdapter._ask_llm_for_commands = (
    _debug_ask_llm_for_commands
)


# ---------------------------------------------------------
# Failure scenario
# ---------------------------------------------------------

runner_name = os.environ["AZURE_VM_NAME"]

prompt = f"""
An Azure DevOps pipeline has failed. Analyze the failure and take corrective action.

## Build Details
- Source       : Azure DevOps
- Project      : Self_Healing_Agent
- Pipeline     : python-agent.git (29) (ID: 29)
- Build Number : 20261001.2
- Build ID     : 301
- Branch       : Hari-var-patch-1
- Repository   : python-agent.git (https://dev.azure.com/VAMDOJOPractice/Self_Healing_Agent/_git/python-agent.git)
- Triggered by : Prayanka Gochipatula
- Start Time   : 2026-10-01T06:40:49.9522911Z
- Finish Time  : 2026-10-01T06:41:20.2494326Z
- Build URL    : https://dev.azure.com/VAMDOJOPractice/c7352528-b101-492f-961f-356dc3c6ce6e/_build/results?buildId=301

## Runner Details
- Runner Name  : {runner_name}

## Failure Summary
Build 20261001.2 failed

- PowerShell exited with code '1'.

## Failed Steps
  - Validate Python 3.13.2 on Runner (type=Task, result=failed)
  - Job (type=Job, result=failed)
  - __default (type=Stage, result=failed)
  - Job (type=Phase, result=failed)

## Failed Step Logs
Task: Validate Python 3.13.2 on Runner — FAILED

Error: Python version mismatch
- Required: 3.13.2
- Found: Python 3.12.12
- Python executable: C:\\Program Files\\LibreOffice\\program\\python.exe

PowerShell: thrown at C:\\Users\\azureuser\\_work\\_temp\\48bcb350-f32b-4715-a428-6e8481c7ea7f.ps1:23 char:3
Exit code: 1

Result: Job failed.

## Instructions
1. Identify the root cause from the logs and failed steps above.
2. Determine which sub-agent or automation capability should handle the fix.
3. Delegate to the appropriate capability and apply the fix.
4. Report what was found and what action was taken.
"""


async def main():
    print("=" * 80)
    print("STARTING FAILURE AGENT E2E TEST")
    print("=" * 80)

    agent = Failure_Agent.get_instance()

    response = await agent.run(
        prompt=prompt,
        task_id=408,
    )

    print("\n" + "=" * 80)
    print("FAILURE AGENT FINAL RESPONSE")
    print("=" * 80)

    if response:
        print(response.text)
    else:
        print("No response from Failure Agent.")


if __name__ == "__main__":
    asyncio.run(main())